Repository SOPT-all/35-COLLABORATION-ANDROID-DAANGN, pull requests merged in 2024-11, with the labels that each got.

#5 [Feat/#4] 컬러 시스템 추가
  app/src/main/java/org/sopt/carrot/ui/theme/Color.kt
  app/src/main/java/org/sopt/carrot/ui/theme/Theme.kt
Labels: ⭐ [FEAT], 민재

#8 [Feat/#6] typography 추가
  app/src/main/java/org/sopt/carrot/presentation/ExampleScreen1/ExampleScreen1.kt
  app/src/main/java/org/sopt/carrot/ui/theme/Theme.kt
  app/src/main/java/org/sopt/carrot/ui/theme/Type.kt
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extrabold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: ⭐ [FEAT], 대현

#10 [Feat/#3] 아이콘 추가
  app/src/main/res/drawable/ic_bottombar_chat_28.xml
  app/src/main/res/drawable/ic_bottombar_life_28.xml
  app/src/main/res/drawable/ic_bottombar_map_28.xml
  app/src/main/res/drawable/ic_bottombar_mypage_28.xml
  app/src/main/res/drawable/ic_chat_lg_18.xml
  app/src/main/res/drawable/ic_chat_sm_18.xml
  app/src/main/res/drawable/ic_chat_solo_18.xml
  app/src/main/res/drawable/ic_check_28.xml
  app/src/main/res/drawable/ic_checkbox_normal_22.xml
  app/src/main/res/drawable/ic_checkbox_selected_22.xml
  app/src/main/res/drawable/ic_delete_circle_18.xml
  app/src/main/res/drawable/ic_delete_orange_18.xml
  app/src/main/res/drawable/ic_direction_down_18.xml
  app/src/main/res/drawable/ic_direction_left_black_28.xml
  app/src/main/res/drawable/ic_direction_left_white_28.xml
  app/src/main/res/drawable/ic_direction_right_28.xml
  app/src/main/res/drawable/ic_help_24.xml
  app/src/main/res/drawable/ic_home_white_28.xml
  app/src/main/res/drawable/ic_like_lg_28.xml
  app/src/main/res/drawable/ic_like_md_18.xml
  app/src/main/res/drawable/ic_like_sm_18.xml
  app/src/main/res/drawable/ic_like_sm_black_18.xml
  app/src/main/res/drawable/ic_location_12.xml
  app/src/main/res/drawable/ic_menu_hamburger_18.xml
  app/src/main/res/drawable/ic_menu_hamburger_28.xml
  app/src/main/res/drawable/ic_menu_kebab_black_18.xml
  app/src/main/res/drawable/ic_menu_kebab_gray_18.xml
  app/src/main/res/drawable/ic_menu_kebab_white_18.xml
  app/src/main/res/drawable/ic_notification_lg_28.xml
  app/src/main/res/drawable/ic_notification_sm_12.xml
  app/src/main/res/drawable/ic_people_18.xml
  app/src/main/res/drawable/ic_plus_sm_18.xml
  app/src/main/res/drawable/ic_reset_18.xml
  app/src/main/res/drawable/ic_search_28.xml
  app/src/main/res/drawable/ic_share_black_28.xml
  app/src/main/res/drawable/ic_share_white_28.xml
  app/src/main/res/drawable/ic_triangle_8.xml
Labels: ⭐ [FEAT], 효은

#14 [Feat/#7] CategoryScreen UI 구현
  app/src/main/java/org/sopt/carrot/core/extension/Modifier.kt
  app/src/main/java/org/sopt/carrot/presentation/NavHost.kt
  app/src/main/java/org/sopt/carrot/presentation/ScreenRoute.kt
  app/src/main/java/org/sopt/carrot/presentation/category/CategoryScreen.kt
  app/src/main/java/org/sopt/carrot/presentation/category/CategoryViewmodel.kt
  app/src/main/java/org/sopt/carrot/presentation/category/component/CategoryBottomBar.kt
  app/src/main/java/org/sopt/carrot/presentation/category/component/CategoryTopBar.kt
  app/src/main/java/org/sopt/carrot/presentation/category/component/item/CategoryCheckBox.kt
  app/src/main/java/org/sopt/carrot/presentation/category/component/section/CategorySelection.kt
  app/src/main/java/org/sopt/carrot/presentation/category/component/section/FilterTabs.kt
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 대현

#12 [Feat/#9] 키워드 검색 UI 구현
  app/src/main/java/org/sopt/carrot/data/model/response/SearchResponse.kt
  app/src/main/java/org/sopt/carrot/data/service/ProductApiService.kt
  app/src/main/java/org/sopt/carrot/presentation/NavHost.kt
  app/src/main/java/org/sopt/carrot/presentation/ScreenRoute.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/TitleSearchScreen.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/EmptyResultMessage.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ErrorContent.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/LoadingIndigator.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductImage.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductInfo.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductItem.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductLikeButton.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductResultContent.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/search/SearchFilterLayout.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/search/SearchKeywordLayout.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/search/SearchScreenToggle.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/search/SearchScreenTopBar.kt
  app/src/main/res/drawable/search_segmentedbar.xml
Labels: ⭐ [FEAT], 민재

#20 [Feat/#15] 판매자 프로필 화면 UI 구현
  app/src/main/java/org/sopt/carrot/presentation/NavHost.kt
  app/src/main/java/org/sopt/carrot/presentation/ScreenRoute.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileScreen.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/SellerFollowDialog.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/SellerProfileTopBar.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/BadgeSection.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/LocationSection.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/MannerSection.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/ReviewSection.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SaleProductSection.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
  app/src/main/res/drawable/ic_ellipse_3.xml
  app/src/main/res/drawable/img_carrier_lg.xml
  app/src/main/res/drawable/img_carrier_md.xml
  app/src/main/res/drawable/img_smile.png
  app/src/main/res/drawable/img_user_lg.xml
  app/src/main/res/drawable/img_user_xs.xml
Labels: ⭐ [FEAT], 대현

#24 [Feat/#19] search api 통신 구현
  app/src/main/java/org/sopt/carrot/core/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/carrot/data/ApiFactory.kt
  app/src/main/java/org/sopt/carrot/data/mapper/SearchMapper.kt
  app/src/main/java/org/sopt/carrot/data/model/response/ResponseRelatedProductInfoDto.kt
  app/src/main/java/org/sopt/carrot/data/model/response/ResponseSearchDto.kt
  app/src/main/java/org/sopt/carrot/data/model/response/SearchResponse.kt
  app/src/main/java/org/sopt/carrot/data/repositoryimpl/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/carrot/data/service/ProductService.kt
  app/src/main/java/org/sopt/carrot/data/service/SearchService.kt
  app/src/main/java/org/sopt/carrot/domain/model/Search.kt
  app/src/main/java/org/sopt/carrot/domain/repository/SearchRepository.kt
  app/src/main/java/org/sopt/carrot/presentation/NavHost.kt
  app/src/main/java/org/sopt/carrot/presentation/ScreenRoute.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/SearchViewModel.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/TitleSearchScreen.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/EmptyResultMessage.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ErrorContent.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductImage.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductInfo.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductItem.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/product/ProductResultContent.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/search/SearchFilterLayout.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/search/SearchScreenToggle.kt
  app/src/main/java/org/sopt/carrot/presentation/titleSearchScreen/components/search/SearchScreenTopBar.kt
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], ♻️ [REFACTOR], 민재

#30 [Feat/#27] 판매자 유저 정보 서버통신 구현
  app/src/main/java/org/sopt/carrot/core/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/carrot/data/mapper/UserMapper.kt
  app/src/main/java/org/sopt/carrot/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/org/sopt/carrot/data/service/UserService.kt
  app/src/main/java/org/sopt/carrot/presentation/NavHost.kt
  app/src/main/java/org/sopt/carrot/presentation/ScreenRoute.kt
  app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
  app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileScreen.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileViewmodel.kt
  app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
  app/src/main/res/drawable/img_user_sm.xml
Labels: ⭐ [FEAT], 대현

#31 [Feat/#29] home 서버통신
  app/build.gradle.kts
  app/src/main/java/org/sopt/carrot/core/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/carrot/data/ApiFactory.kt
  app/src/main/java/org/sopt/carrot/data/mapper/HomeProductMapper.kt
  app/src/main/java/org/sopt/carrot/data/model/response/ResponseHomeDto.kt
  app/src/main/java/org/sopt/carrot/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/org/sopt/carrot/data/service/HomeService.kt
  app/src/main/java/org/sopt/carrot/domain/model/HomeProduct.kt
  app/src/main/java/org/sopt/carrot/domain/repository/HomeRepository.kt
  app/src/main/java/org/sopt/carrot/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/carrot/presentation/main/MainViewModel.kt
  app/src/main/java/org/sopt/carrot/presentation/main/RandomTimeDistance.kt
  app/src/main/java/org/sopt/carrot/presentation/main/component/ProductList.kt
Labels: ⭐ [FEAT], ⛏️서버통신, 효은
